include(cdat_common_environment)
set(ENV{PATH} ${CMAKE_INSTALL_PREFIX}/bin:${CMAKE_INSTALL_PREFIX}/Externals/bin:$ENV{PATH})
set(ENV{HDF5_DIR} ${CMAKE_INSTALL_PREFIX}/Externals)
set(ENV{HDF5_INCDIR} ${CMAKE_INSTALL_PREFIX}/Externals/include)
set(ENV{HDF5_LIBDIR} ${CMAKE_INSTALL_PREFIX}/Externals/lib)
set(ENV{NETCDF4_DIR} ${CMAKE_INSTALL_PREFIX}/Externals)
set(ENV{NETCDF4_INCDIR} ${CMAKE_INSTALL_PREFIX}/Externals/include)
set(ENV{NETCDF4_LIBDIR} ${CMAKE_INSTALL_PREFIX}/Externals/lib)

ExternalProject_Add(netcdf4
  DOWNLOAD_DIR ${CDAT_PACKAGE_CACHE_DIR}
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/build/netCDF4
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/build/netCDF4
  URL ${NETCDF4_SOURCE}
  URL_MD5 ${NETCDF4_MD5}
  CONFIGURE_COMMAND "" 
  BUILD_COMMAND ""
  UPDATE_COMMAND ""
  INSTALL_COMMAND env HDF5_DIR=$ENV{HDF5_DIR} HDF5_LIBDIR=$ENV{HDF5_LIBDIR} HDF5_INCDIR=$ENV{HDF5_INCDIR}
  NETCDF4_DIR=$ENV{NETCDF4_DIR} NETCDF4_LIBDIR=$ENV{NETCDF4_LIBDIR} NETCDF4_INCDIR=$ENV{NETCDF4_INCDIR}
  ${PYTHON_EXECUTABLE} setup.py install --prefix=${PYTHONUSERBASE}
  DEPENDS
    ${netcdf4_deps}
  ${ep_log_options}
  )

