set(PyTables_deps ${pkgconfig_pkg} ${python_pkg} ${cython_pkg} ${numexpr_pkg} ${numpy_pkg} ${hdf5_pkg} )
if (NOT CDAT_USE_SYSTEM_LIBXML2)
    list(APPEND PyTables_deps ${libxml2_pkg})
endif()
if (NOT CDAT_USE_SYSTEM_LIBXSLT)
    list(APPEND PyTables_deps ${libxslt_pkg})
endif()
if (NOT CDAT_USE_SYSTEM_ZLIB)
    list(APPEND PyTables_deps ${zlib_pkg})
endif()
